name: Spring Boot CI Template

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
    secrets: {}

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Cancelar workflows previos
        uses: styfle/cancel-workflow-action@0.12.1
    
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: mvn clean verify

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports
