name: Spring Boot CI Template

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
    secrets: {}

jobs:
  avoid-redundancy:
    runs-on: ubuntu-24.04
    steps:
      - name: Cancelar workflows previos
        uses: styfle/cancel-workflow-action@0.12.1

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
      - run: mvn clean package -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*.jar

  test:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - run: mvn test
